Repository nickhartdev/exquisite-corpse-server, pull requests merged in 2020-09, with the labels that each got.

#4 Database/ge env setup
  .gitignore
  database.sql
  db/migrations/20200909193738_initial.js
  db/migrations/20200909200931_add-publisher.js
  db/migrations/20200910165134_update_initial.js
  db/migrations/20200910185000_drop_foreign_prompt.js
  db/seeds/dev/prompts_seed.js
  knexfile.js
  package-lock.json
  package.json
  pull_request_template.md
  server.js
Labels: database

#13 Fix migration redundancies
  db/migrations/20200909193738_initial.js
  db/migrations/20200910165134_update_initial.js
  db/migrations/20200910185000_drop_foreign_prompt.js
  db/migrations/20200912172438_bug_fix.js
  knexfile.js
Labels: bugfix

#16 Seed/abd create prompts
  db/migrations/20200913164419_increase_varchar.js
  db/seeds/dev/prompts_seed.js
Labels: database, setup

#17 Flesh out the server
  .babelrc
  db/migrations/20200913121733_author_bios.js
  db/migrations/20200913122453_story_authors+datatype.js
  db/migrations/20200913124040_story_completion.js
  db/seeds/dev/authors_seed.js
  db/seeds/dev/stories_seed.js
  package.json
  server-helpers.js
  server.js
Labels: database, enhancement, setup

#21 Make findAuthorByUsername dynamic
  server-helpers.js
  server.js
Labels: database, enhancement

#24 Grey response fix
  db/seeds/dev/authors_seed.js
  db/seeds/dev/prompts_seed.js
  db/seeds/dev/stories_seed.js
  knexfile.js
  server-helpers.js
  server.js
Labels: database
